import type { Metadata } from "next";
import { Syne, TASA_Orbiter, Zen_Kaku_Gothic_Antique } from "next/font/google";
import "./globals.css";

const syne = Syne({
    variable: "--font-syne",
    subsets: ["latin"],
});

const tasaOrbiter = TASA_Orbiter({
    variable: "--font-tasa-orbiter",
    subsets: ["latin"],
});

const zenKakuGothicAntique = Zen_Kaku_Gothic_Antique({
    variable: "--font-zen-kaku-gothic-antique",
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ja"
            className={`${syne.variable} ${tasaOrbiter.variable} ${zenKakuGothicAntique.variable}`}
        >
            <body className="font-sans min-h-screen bg-background text-foreground antialiased">
                <main>{children}</main>
            </body>
        </html>
    );
}
